batch_id: "P5_385-432"
panel_id: "p5"
base_path: "/mnt/Data4"
variants_directory: "variants/haplotyper"
intervals_directory: "/mnt/Data1/targeted_sequencing/intervals"
transcript_file_path: "/mnt/Data1/targeted_sequencing/v5_transcript_list.txt"
unwanted_file_path: "../configuration/unwanted_variants.csv"
sample_list_path: "../configuration/sample_list.csv"
coverage_cutoff: "30"
